trigger:
  branches:
    include:
      - main

pool:
  name: default
#  vmImage: 'windows-latest'

variables:
  - name: subscription_name
    value: 'Azure'
  - name: bicep_filepath
    value: 'infra/Deployment.bicep'
  - name: arm_template_filepath
    value: '$(Pipeline.Workspace)/BicepArtifacts/services.json'
  - name: app_name
    value: 'lockingdemo'

stages:
- stage: Build

  jobs:
  - job: Bicep
    steps:
      - task: AzureCLI@2
        displayName: Build ARM Template from bicep file
        inputs:
          azureSubscription: '${{variables.subscription_name}}'
          scriptType: ps
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            az bicep build --file infra/Deployment.bicep

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Deploy ARM Templates'
        inputs:
          azureResourceManagerConnection: 'Azure'
          subscriptionId: '92dba6c6-2cf8-46ad-9d75-8674f0f66b9a'
          resourceGroupName: 'LockingDemo'
          location: 'Australia East'
          csmFile: infra/Deployment.json
          csmParametersFile: infra/DeploymentParameters.json
          deploymentMode: Incremental
          
  - job: AzureFunction
    dependsOn: 
    - Bicep
    steps:      
      - task: DotNetCoreCLI@2
        displayName: build
        inputs:
          command: 'build'
          projects: src/NDC21CosmosRedisDemo.sln
          arguments: --output $(System.DefaultWorkingDirectory)/published_backend --configuration Release

      - task: ArchiveFiles@2
        displayName: 'Archive API artifact files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/published_backend'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/api.$(Build.BuildId).zip
          replaceExistingArchive: true

      - task: AzureFunctionApp@1
        displayName: 'Azure functions App deploy'
        inputs:
          azureSubscription: '${{variables.subscription_name}}'
          appType: 'functionApp'
          appName: '${{variables.app_name}}'
          package: $(Build.ArtifactStagingDirectory)/api.$(Build.BuildId).zip 
          deploymentMethod: 'runFromPackage'

